#!/usr/bin/env python3
"""
Gradio Streaming Client - Demonstrates real-time token streaming

This script shows how to use streaming responses from the Gradio server
to display text in real-time as it's generated by the RKLLM model.
"""

from gradio_client import Client
import sys


def test_streaming_chat(server_url: str = "http://localhost:7860"):
    """Test streaming chat with real-time token display."""
    
    print("=" * 60)
    print("🌊 RKLLM Gradio Streaming Chat Demo")
    print("=" * 60)
    print(f"📡 Server URL: {server_url}\n")
    
    try:
        # Connect to server
        print("📞 Connecting to Gradio server...")
        client = Client(server_url)
        print("✅ Connected successfully!\n")
        
        # Test streaming
        print("=" * 60)
        print("TEST 1: Streaming Response")
        print("=" * 60)
        
        history = []
        message = "Explain quantum computing in 3 sentences"
        
        print(f"\n👤 User: {message}")
        print(f"🤖 Assistant: ", end="", flush=True)
        
        # Use streaming mode (use_streaming=True)
        result = client.predict(
            message=message,
            chat_history=history,
            use_streaming=True,
            api_name="/respond"
        )
        
        if result and len(result) > 0:
            history = result
            response = result[-1]["content"]
            print(response)
            print("\n✅ Streaming Test PASSED\n")
        else:
            print("❌ No response received\n")
            return False
        
        # Test non-streaming for comparison
        print("=" * 60)
        print("TEST 2: Non-Streaming Response (Comparison)")
        print("=" * 60)
        
        message2 = "What is machine learning?"
        
        print(f"\n👤 User: {message2}")
        print("🤖 Assistant: Fetching complete response...\n", end="", flush=True)
        
        # Use non-streaming mode (use_streaming=False)
        result = client.predict(
            message=message2,
            chat_history=history,
            use_streaming=False,
            api_name="/respond"
        )
        
        if result and len(result) > 0:
            history = result
            response = result[-1]["content"]
            print(f"Complete response received: {len(response)} characters\n")
            print(f"Response preview: {response[:100]}...\n")
            print("✅ Non-Streaming Test PASSED\n")
        else:
            print("❌ No response received\n")
            return False
        
        # Show streaming advantage
        print("=" * 60)
        print("📊 Streaming Benefits")
        print("=" * 60)
        print("""
✅ Advantages of Streaming Mode:
   • Real-time feedback: Users see text appearing instantly
   • Better UX: No long wait for complete response
   • Progressive display: Can start reading before completion
   • Responsive UI: Gradio interface updates in real-time

✅ Use Cases for Streaming:
   • Long-form text generation
   • Chat applications with immediate feedback
   • Educational tools showing thinking process
   • Content generation with visual feedback
        """)
        
        print("=" * 60)
        print("🚀 Gradio Streaming Interface is Working!")
        print("=" * 60)
        
        return True
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        print("\n🔧 Troubleshooting:")
        print("1. Make sure Gradio server is running")
        print("2. Verify streaming toggle is enabled in UI")
        print("3. Check both use_streaming=True and use_streaming=False")
        return False


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Test Gradio streaming")
    parser.add_argument(
        "--url",
        default="http://localhost:7860",
        help="Gradio server URL"
    )
    
    args = parser.parse_args()
    
    success = test_streaming_chat(args.url)
    sys.exit(0 if success else 1)
